### ISSUE TITLE
Pagination and load more for cards

### ISSUE THREAD

**Issue by summerhays** [Montreal-Quakers/website#12]
Pagination and load more for cards and posts, filter cards?

**Comment by summerhays** [comment]
https://disjfa.github.io/bootstrap-tricks/intersection-observer/ 

https://github.com/disjfa/bootstrap-tricks/blob/5aced25e1ee3d913839954a83ffa94b5bc7cc20e/intersection-observer/index.html

Animations for cards so they look cooler on the page

**Comment by mtlquakers** [comment]
Done
